language: node_js
node_js:
  - "stable"
env:
  global:
    - export DATABASE_TEST_URL=postgres://postgres@localhost:5432/travis_ci_test

services:
- postgresql

before_script:  
- psql -c 'create database travis_ci_test;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

install:
- npm install

script:
- npm run test:coverage

cache:
  directories:
  - node_modules

after_success:
- npm run coveralls

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
