version: "3.7"

services:
  web:
    container_name: jamb-prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:80
    environment:
      - NODE_ENV=production
      # - BASE_URL=${BASE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
